name: teton_meal_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.1
  # firebase_auth removed
  cloud_firestore: ^5.6.2
  share_plus: ^10.1.4
  firebase_dynamic_links: ^6.1.1
  intl: ^0.20.2
  firebase_analytics: ^11.4.1
  provider: ^6.0.3
  fl_chart: ^0.70.2
  table_calendar: ^3.2.0
  firebase_messaging: ^15.2.2
  fluttertoast: ^8.0.8
  rxdart: ^0.28.0
  uuid: ^4.3.3
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
